[package]
name = "rastra"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Modern MCBE server software written in Rust"

[dependencies]
bedrock-rs = { path = "../bedrock-rs", features = ["full"] }
tokio = { version = "1.37.0", features = ["full"] }